import {
  Accessibility,
  Plus,
  ArrowRight,
  PersonStanding,
  CalendarDays,
  Calendar,
  Phone,
  Camera,
  MessageCircle,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  X,
  Gem,
  CalendarCheck,
  Smile,
  Quote,
  Users,
  MapPin,
  Mail,
  Map,
  ClipboardPlus,
  Stethoscope,
  Menu,
  Award,
  Clapperboard,
  User,
  PhoneCall,
  Play,
  PlayCircle,
  Globe,
  QrCode,
  Minus,
  Clock,
  Sparkles,
  Send,
  Share2,
  Flower2,
  Star,
  Headset,
  ChevronsUpDown,
  Video,
  GraduationCap,
  Store,
  type LucideIcon,
} from "lucide-react";

/**
 * Maps the 46 Material Symbols Outlined icon names used across the legacy
 * site to their closest lucide-react equivalent. A few (self_improvement,
 * spa, body_fat, unfold_more) have no literal match — closest-fit substitutes.
 */
export const iconMap = {
  accessibility_new: Accessibility,
  add: Plus,
  arrow_forward: ArrowRight,
  body_fat: PersonStanding,
  calendar_month: CalendarDays,
  calendar_today: Calendar,
  call: Phone,
  camera_alt: Camera,
  chat: MessageCircle,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  diamond: Gem,
  event_available: CalendarCheck,
  face: Smile,
  format_quote: Quote,
  groups: Users,
  location_on: MapPin,
  mail: Mail,
  map: Map,
  medical_information: ClipboardPlus,
  medical_services: Stethoscope,
  menu: Menu,
  military_tech: Award,
  movie: Clapperboard,
  person: User,
  phone: Phone,
  phone_in_talk: PhoneCall,
  photo_camera: Camera,
  play_arrow: Play,
  play_circle: PlayCircle,
  public: Globe,
  qr_code_2: QrCode,
  remove: Minus,
  schedule: Clock,
  school: GraduationCap,
  self_improvement: Sparkles,
  send: Send,
  share: Share2,
  spa: Flower2,
  star: Star,
  storefront: Store,
  support_agent: Headset,
  unfold_more: ChevronsUpDown,
  video_library: Video,
  workspace_premium: Award,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;
